### ISSUE TITLE
Parsing Error Using YML Configs for Feature Data Types

### ISSUE THREAD

**Issue by tonytusharjr** [bcodell/dbt-activity-schema#22]
The use of defining data types for features in a yml config versus the model config:

```
version: 2

models:

  - name: prefix_1__activity_name
    config:
      stream: stream_1
      data_types:
        feature_1: {{type_int()}}
        feature_2: {{type_string()}}
        feature_3: {{type_timestamp()}}
```

Results in a parsing error at compilation time:
```
Parsing Error
  Error reading dbt_project: sub_directory/_an_activity_model.yml - Runtime Error
    Syntax error near line 8
    ------------------------------
    5  |     config:
    6  |       stream: stream_1
    7  |       data_types:
    8  |         feature_1: {{type_int()}}
    9  |         feature_2: {{type_string()}}
    10 |         feature_3: {{type_string()}}
    
    Raw Error:
    ------------------------------
    while constructing a mapping
      in "<unicode string>", line 8, column 23
    found unhashable key
      in "<unicode string>", line 8, column 24
```
I don't think we can directly define a jinja bracket function in the yml as currently in the example.
