### ISSUE TITLE
bug - build_activity macro needs explicitly set null_columns when using anonymous_customer_id

### ISSUE THREAD

**Issue by awoehrl** [bcodell/dbt-activity-schema#47]
I forgot about this, because I added the null_columns attribute when doing my first tests with dbt-aql. If I don't explicitly set `null_columns`, my `anonymous_customer_column` will be nulled. Not sure if it's a bug or missing in the documentation though.

**dbt_project**
```
vars:
  dbt_aql:
    column_configuration:
      included_optional_columns:
        - link
        - revenue_impact
      column_aliases:
        feature_json: feature_json
    streams:
      customer_stream:
        customer_id_alias: customer_id
        anonymous_customer_id_alias: anonymous_customer_id
        model_prefix: customer__
        skip_stream: true
      test_stream:
        customer_id_alias: entity_id
        anonymous_customer_id_alias: anonymous_entity_id
        model_prefix: test__
      third_stream:
        customer_id_alias: entity_id
        model_prefix: third__
```

**Example activity**
```
{{
    config(
        materialized='table',
        stream='test_stream',
        data_types={
            'article_id': type_string(),
        }
        
    )
}}

with base as (
  select
    distinct
    event_id || start_tstamp || app_id   as page_view_start_tstamp_id,
    user_id                                           as {{ dbt_aql.customer_column('test_stream') }},
    domain_userid                               as {{ dbt_aql.anonymous_customer_column('test_stream') }},
    start_tstamp                                   as {{ dbt_aql.schema_columns().ts }},

    --features_json
    content.article_id                            as article_id

  from {{ ref('page_views_extended') }}
  where date(start_tstamp) >= current_date() - 28
)

{{ dbt_aql.build_activity(
    cte='base',
    unique_id_column='page_view_start_tstamp_id'
) }}
```

**Output**
Here anonymous_entity_id will be nulled:  `cast(null as STRING) as anonymous_entity_id`

```
    create or replace table `dwh-project`.`dev_awoehrl`.`test__viewed_page2`
      
    
    

    OPTIONS(
      expiration_timestamp=TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 168 hour),
    
      description=""""""
    )
    as (
      

with base as (
  select
    distinct
    event_id || start_tstamp || app_id as page_view_start_tstamp_id,
    user_id                    as entity_id,
    domain_userid              as anonymous_entity_id,
    start_tstamp               as ts,

    --features_json
    content.article_id         as article_id

  from `dwh-project`.`dev_awoehrl`.`page_views_extended`
  where
    date(start_tstamp) >= current_date() - 28
    
)

select
    cast(cast(to_hex(md5(cast(coalesce(cast(entity_id as STRING), '_dbt_utils_surrogate_key_null_') || '-' || coalesce(cast(ts as STRING), '_dbt_utils_surrogate_key_null_') || '-' || coalesce(cast('viewed page2' as STRING), '_dbt_utils_surrogate_key_null_') || '-' || coalesce(cast(page_view_start_tstamp_id as STRING), '_dbt_utils_surrogate_key_null_') as STRING))) as STRING) as STRING) as activity_id
    , cast(entity_id as STRING) as entity_id
    , cast(null as STRING) as anonymous_entity_id
    , cast('viewed page2' as STRING) as activity
    , cast(ts as TIMESTAMP) as ts
    , cast(null as INT64) as revenue_impact
    , cast(null as STRING) as link
    , to_json(struct(
        article_id as article_id
        )) as feature_json
    , row_number() over (
        partition by entity_id
        order by ts, cast(to_hex(md5(cast(coalesce(cast(entity_id as STRING), '_dbt_utils_surrogate_key_null_') || '-' || coalesce(cast(ts as STRING), '_dbt_utils_surrogate_key_null_') || '-' || coalesce(cast('viewed page2' as STRING), '_dbt_utils_surrogate_key_null_') || '-' || coalesce(cast(page_view_start_tstamp_id as STRING), '_dbt_utils_surrogate_key_null_') as STRING))) as STRING)
    ) as activity_occurrence
    , lead(cast(ts as TIMESTAMP)) over (
        partition by entity_id
        order by ts, cast(to_hex(md5(cast(coalesce(cast(entity_id as STRING), '_dbt_utils_surrogate_key_null_') || '-' || coalesce(cast(ts as STRING), '_dbt_utils_surrogate_key_null_') || '-' || coalesce(cast('viewed page2' as STRING), '_dbt_utils_surrogate_key_null_') || '-' || coalesce(cast(page_view_start_tstamp_id as STRING), '_dbt_utils_surrogate_key_null_') as STRING))) as STRING)
    ) as activity_repeated_at
from base


    );  
```

**Explicitly setting null_columns works:**

```
{{
    config(
        materialized='incremental',
        stream='test_stream',
        data_types={
            'article_id': type_string(),
        }
        
    )
}}

with base as (
  select
    distinct
    event_id || start_tstamp || app_id as page_view_start_tstamp_id,
    user_id                    as {{ dbt_aql.customer_column('test_stream') }},
    domain_userid              as {{ dbt_aql.anonymous_customer_column('test_stream') }},
    start_tstamp               as {{ dbt_aql.schema_columns().ts }},

    --features_json
    content.article_id         as article_id

  from {{ ref('page_views_extended') }}
  where
    date(start_tstamp) >= current_date() - 28
    {% if is_incremental() %}
      and date(start_tstamp)
      > coalesce((select max(date(start_tstamp)) from {{ this }}), '1900-01-01')
    {% endif %}
)

{{ dbt_aql.build_activity(
    cte='base',
    unique_id_column='page_view_start_tstamp_id',
    null_columns=['link','revenue_impact']
) }}

```
